### ISSUE TITLE
Create or update a Checkmk data source using HTTP API

### ISSUE THREAD

**Issue by shi-ron** [Checkmk/grafana-checkmk-datasource#255] opened 2024-08-20 12:41 UTC
Hi,

grafana provides a HTTP API to create or update a data source. 
Here is the doc: https://grafana.com/docs/grafana/latest/developers/http_api/data_source/

Does Checkmk support creating or updating using API? Can you give me a request example?

Thanks!

**Comment by BenediktSeidl** [comment] 2024-08-21 06:09
So you want to create a Checkmk data source in Grafana via the Grafana HTTP-API? This should be possible for all data sources whether they are built in or plugins. I would create one data source manually and then use the API to receive the data, to learn about the data format. Then you can adapt the data and use another endpoint to create a new data source.

We currently have limited resources to maintain this plugin, so please understand that I can not help you with generic Grafana issues not directly caused by this plugin. This is why I will close this issue. If I misunderstood your question, please comment and I will reopen it.

**Closed by BenediktSeidl** 2024-08-21 06:09 UTC
