### ISSUE TITLE
Check_MK Raw: not able to show graphs for multi selected variable

### ISSUE THREAD

**Issue by roflmao** [Checkmk/grafana-checkmk-datasource#258] opened 2024-09-04 11:32 UTC
By choosing a single value from a variable used in Service field it works, if i choose multiple values i get;

```
Bad Request Cannot calculate graph recipes: No matching entries found for query: GET services Columns: perf_data metrics check_command Filter: host_name = db-main-002.X.com Filter: service_description = {DFS_dfs-111,DFS_dfs-123}
```

Is this by design or am i doing it completely wrong?

Using plugin version 3.3.0 against Check_MK Raw Edition 2.2.0p31 and Grafana v10.4.5

**Comment by BenediktSeidl** [comment] 2024-09-04 12:13
Can you please check if this is duplicate of #247? If this is the case, please close your issue and add a comment (or a :+1:) to #247 to rise awareness that this is a feature that multiple users want.

**Comment by roflmao** [comment] 2024-09-04 12:17
@BenediktSeidl It looks related, though i'm not on the commercial plugin due to Raw. I'm not able to use regex or wildcard as i understand?

**Closed** 2024-09-04 13:33 UTC
